import type { PortfolioContent } from './types';

export const en: PortfolioContent = {
	meta: {
		title: 'Jonatas Pedraza — Software Engineer',
		description:
			'Software Engineer focused on backend, architecture, cloud, and DevOps. Experience across credit, payments, delivery, telecom, and video platforms.',
	},
	nav: {
		about: 'About',
		experience: 'Experience',
		skills: 'Skills',
		contact: 'Contact',
		resume: 'Resume',
		versionPreview: 'Layout versions',
	},
	hero: {
		eyebrow: 'Jonatas Pedraza',
		headline: 'Software Engineer',
		tagline:
			'Backend, architecture, and cloud for products that must scale with reliability.',
		ctaContact: 'Get in touch',
		ctaResume: 'Download resume',
	},
	about: {
		title: 'About',
		body: 'Software Engineer with a path across backend, architecture, and DevOps, building platforms that must scale with reliability — credit, payments, delivery, telecom, video, and data-oriented products. I work end to end: from framing the problem and shaping the solution through implementation, observability, and production support. I am a generalist with judgment: choose the right tool for the challenge, keep architecture maintainable, and ship closely with product, design, and operations. I use generative AI tools as day-to-day leverage — to accelerate exploration and delivery — while owning trade-offs, quality, and what actually ships.',
	},
	experience: {
		title: 'Experience',
		items: [
			{
				company: 'Nuvemshop',
				companyUrl: 'https://www.nuvemshop.com.br/',
				role: 'Software Engineer',
				period: 'Mar 2024 — Present',
				location: 'São Paulo, Brazil',
				summary:
					'At Nuvemshop I evolve the credit platform — from offering and management through day-to-day operations. The work spans backend and frontend: I build scalable, reliable features, integrate partner APIs for the credit engine (system communication, data exchange, and automation of analysis and approval), and develop the credit frontend with React, TypeScript, Figma, and Playwright alongside design. In a lean squad with product, design, and operations, I also ship internal back-office tools that improve processes and speed up value delivery. When production breaks, I investigate with Datadog (metrics, logs, and root cause) and use generative AI tools as leverage in the development workflow — while still owning quality and what reaches the user.',
				technologies: [
					'TypeScript',
					'Node.js',
					'React',
					'Figma',
					'Playwright',
					'PostgreSQL',
					'Redis',
					'AWS',
					'Datadog',
				],
			},
			{
				company: 'Delivery Much Brasil',
				companyUrl: 'https://www.deliverymuch.com.br/',
				role: 'Software Architect',
				period: 'Jun 2021 — Feb 2024',
				location: 'Santa Catarina, Brazil',
				summary:
					'As a software architect I designed and implemented food-delivery solutions as microservices on AWS, with constant attention to scale, performance, security, and maintainability. A core part of the role was turning business needs into technical decisions: interviews, refinements, and alignment with stakeholders, producing clear specs for the team. I supported tech leads on coding standards, documentation (diagrams and guides), continuous integration, and agile practices. In critical moments I joined squads hands-on — legacy systems, complex integrations — helping unblock high-priority deliveries without losing the architectural thread.',
				technologies: [
					'NestJS',
					'Node.js',
					'TypeScript',
					'Docker',
					'MongoDB',
					'PostgreSQL',
					'Redis',
					'Elasticsearch',
				],
			},
			{
				company: 'Pagar.me',
				companyUrl: 'https://www.pagar.me/',
				role: 'Software Engineer',
				period: 'Aug 2017 — Jun 2021',
				location: 'São Paulo, Brazil',
				summary:
					'On Pagar.me’s SRE team I worked on online payment systems under real availability and scale pressure. Day to day mixed architecture, development, and infrastructure evolution for distributed applications — including supporting squads on Elasticsearch cluster design and operations. I automated provisioning and delivery with Terraform, Packer, Ansible, and Docker on AWS, always aiming at the same outcomes: performance, reliability, and room to grow without production surprises.',
				technologies: [
					'Python',
					'JavaScript',
					'Go',
					'C#',
					'AWS',
					'Terraform',
					'Packer',
					'Ansible',
					'Docker',
				],
			},
			{
				company: 'Nokia Networks',
				companyUrl: 'https://www.nokia.com/networks/',
				role: 'System Integration Engineer',
				period: 'Dec 2015 — Aug 2017',
				location: 'Rio de Janeiro, Brazil',
				summary:
					'At Nokia I integrated systems for telecom operators: developing, provisioning, orchestrating, and configuring solutions that had to talk across heterogeneous environments. I worked on third-party IoT integrations and ETL pipelines with Greenplum and MySQL, connecting data sources to operational flows. To cut manual work and risk, I automated Linux environments with Ansible and Shell Script, applying cloud practices, Git, Elasticsearch, and design patterns aimed at scale and maintainability.',
				technologies: [
					'Ansible',
					'Shell Script',
					'Linux',
					'MySQL',
					'Greenplum',
					'Elasticsearch',
					'Git',
				],
			},
			{
				company: 'Globo.com',
				companyUrl: 'https://www.globo.com/',
				role: 'Software Engineer',
				period: 'Nov 2014 — Nov 2015',
				location: 'Rio de Janeiro, Brazil',
				summary:
					'On Globo.com’s video platform I built and maintained backend services and APIs for live and on-demand delivery, focused on performance, scale, and resilience — where latency and stability truly matter. I also contributed to DevOps on automating and improving CI/CD pipeline efficiency, shortening the path from code to production. The work spanned microservices and distributed systems, with a data, cache, and load-balancing stack (PostgreSQL, MongoDB, Redis, Elasticsearch, Nginx) on top of Python, Node.js, and Docker.',
				technologies: [
					'Python',
					'Node.js',
					'JavaScript',
					'Redis',
					'Docker',
					'PostgreSQL',
					'MongoDB',
					'Elasticsearch',
					'Nginx',
				],
			},
			{
				company: 'Neemu',
				companyUrl: 'https://www.linx.com.br/',
				role: 'Software Developer',
				period: 'Feb 2013 — Oct 2014',
				location: 'Manaus, Brazil',
				summary:
					'At Neemu I worked on the Big Data team building data-acquisition services for scalable, distributed systems — foundations that must absorb volume without losing reliability. I also joined DevOps, automating routines, improving continuous delivery/deployment pipelines, and managing AWS resources. Day to day mixed Node.js and JavaScript with MySQL, PostgreSQL, MongoDB, and Redis, plus Shell Script on Linux, Docker, and Git. I applied microservices, design patterns, and cloud practices so performance, scale, and maintainability stayed at the center of the decisions.',
				technologies: [
					'Node.js',
					'JavaScript',
					'MySQL',
					'PostgreSQL',
					'MongoDB',
					'Redis',
					'Docker',
					'AWS',
					'Shell Script',
				],
			},
			{
				company: 'INdT',
				companyUrl: 'https://indt.org.br/',
				role: 'Software Developer',
				period: 'Apr 2012 — Feb 2013',
				location: 'Manaus, Brazil',
				summary:
					'At INdT (Nokia Institute of Technology) I was on the Cloud & Backend team developing backend services and mobile applications. I built scalable REST APIs integrated with MySQL, using Node.js, JavaScript, Java, and C++ depending on the problem. Development and production ran on Linux, with heavy Shell Script use for automation. Projects demanded close collaboration with other teams, agile practices with Scrum, and continuous improvement of architecture and processes — with Git and design patterns keeping the codebase maintainable.',
				technologies: [
					'Node.js',
					'JavaScript',
					'Java',
					'C++',
					'MySQL',
					'Linux',
					'Shell Script',
					'Git',
				],
			},
		],
	},
	skills: {
		title: 'Skills',
		groups: [
			{
				title: 'Backend & APIs',
				items: [
					'Node.js',
					'TypeScript',
					'NestJS',
					'Python',
					'Go',
					'C#',
					'REST',
					'Microservices',
				],
			},
			{
				title: 'Architecture',
				items: [
					'Clean Code',
					'Clean Architecture',
					'Design patterns',
					'Distributed systems',
					'Scalability',
					'Resilience',
				],
			},
			{
				title: 'Cloud & DevOps',
				items: [
					'AWS',
					'Docker',
					'Terraform',
					'Packer',
					'Ansible',
					'CI/CD',
					'Linux',
					'Shell Script',
				],
			},
			{
				title: 'Data & Observability',
				items: [
					'PostgreSQL',
					'MySQL',
					'MongoDB',
					'Redis',
					'Elasticsearch',
					'Datadog',
					'Metrics',
					'Logs',
				],
			},
		],
	},
	contributions: {
		title: 'Activity on GitHub',
		summary: '{total} public contributions in the last year.',
		profileLink: 'View GitHub profile',
		legendLabel: 'Activity level',
		legendLess: 'Less',
		legendMore: 'More',
		contributionSingular: 'contribution',
		contributionPlural: 'contributions',
	},
	contact: {
		title: 'Contact',
		body: 'Open to conversations about engineering, architecture, and opportunities. Prefer email or LinkedIn.',
		ctaEmail: 'Send email',
		labels: {
			email: 'Email',
			linkedin: 'LinkedIn',
			github: 'GitHub',
			location: 'Location',
		},
	},
	footer: {
		rights: 'Jonatas Pedraza. All rights reserved.',
		brandNote: 'Visual identity: Mandril Solutions',
	},
	wire: {
		role: 'role',
		name: 'name',
		summary: 'summary',
		activityGithub: 'activity / github',
		about: '01 / about',
		experience: '02 / experience',
		skills: '03 / skills',
	},
};
