import type { PortfolioContent } from './types';

export const es: PortfolioContent = {
	meta: {
		title: 'Jonatas Pedraza — Ingeniero de Software',
		description:
			'Ingeniero de Software enfocado en backend, arquitectura, cloud y DevOps. Experiencia en crédito, pagos, delivery, telecom y video.',
	},
	nav: {
		about: 'Sobre mí',
		experience: 'Experiencia',
		skills: 'Competencias',
		contact: 'Contacto',
		resume: 'Currículum',
		versionPreview: 'Versiones de layout',
	},
	hero: {
		eyebrow: 'Jonatas Pedraza',
		headline: 'Ingeniero de Software',
		tagline:
			'Backend, arquitectura y cloud para productos que deben escalar con confiabilidad.',
		ctaContact: 'Hablar conmigo',
		ctaResume: 'Descargar currículum',
	},
	about: {
		title: 'Sobre mí',
		body: 'Ingeniero de Software con trayectoria en backend, arquitectura y DevOps, construyendo plataformas que deben escalar con confiabilidad — crédito, pagos, delivery, telecom, video y productos orientados a datos. Trabajo de punta a punta: desde entender el problema y diseñar la solución hasta la implementación, observabilidad y soporte en producción. Perfil generalista con criterio: elijo la herramienta adecuada para el desafío, priorizo una arquitectura sostenible y colaboro de cerca con producto, diseño y operaciones. Uso herramientas de IA generativa como apalancamiento en el día a día — para acelerar exploración y entrega — sin soltar la responsabilidad sobre trade-offs, calidad y lo que realmente llega a producción.',
	},
	experience: {
		title: 'Experiencia',
		items: [
			{
				company: 'Nuvemshop',
				role: 'Ingeniero de Software',
				period: 'Mar 2024 — Actual',
				location: 'São Paulo, Brasil',
				summary:
					'En Nuvemshop evoluciono la plataforma de crédito — desde la oferta y la gestión hasta las operaciones del día a día. El trabajo abarca backend y frontend: construyo funcionalidades escalables y confiables, integro APIs de socios para el motor de crédito (comunicación entre sistemas, intercambio de datos y automatización de análisis y aprobación) y desarrollo el frontend de crédito con React, TypeScript, Figma y Playwright, junto a diseño. En un squad reducido con producto, diseño y operaciones, también entrego herramientas internas de backoffice que mejoran procesos y aceleran valor. Cuando algo falla en producción, investigo con Datadog (métricas, logs y causa raíz) y uso herramientas de IA generativa como apalancamiento en el flujo de desarrollo — sin soltar la responsabilidad sobre calidad y lo que llega al usuario.',
				technologies: [
					'TypeScript',
					'Node.js',
					'React',
					'Figma',
					'Playwright',
					'PostgreSQL',
					'Redis',
					'AWS',
					'Datadog',
				],
			},
			{
				company: 'Delivery Much Brasil',
				role: 'Arquitecto de Software',
				period: 'Jun 2021 — Feb 2024',
				location: 'Santa Catarina, Brasil',
				summary:
					'Como arquitecto diseñé e implementé soluciones de food delivery como microservicios en AWS, con atención constante a escala, rendimiento, seguridad y mantenibilidad. Una parte central del rol era traducir el negocio en decisiones técnicas: entrevistas, refinamientos y alineaciones con stakeholders, produciendo especificaciones claras para el equipo. Apoyé a tech leads con estándares de código, documentación (diagramas y guías), integración continua y prácticas ágiles. En momentos críticos entré hands-on en squads con legado e integraciones complejas, ayudando a desbloquear entregas de alta prioridad sin perder el hilo de la arquitectura.',
				technologies: [
					'NestJS',
					'Node.js',
					'TypeScript',
					'Docker',
					'MongoDB',
					'PostgreSQL',
					'Redis',
					'Elasticsearch',
				],
			},
			{
				company: 'Pagar.me',
				role: 'Ingeniero de Software',
				period: 'Ago 2017 — Jun 2021',
				location: 'São Paulo, Brasil',
				summary:
					'En el equipo de SRE de Pagar.me trabajé en sistemas de pagos online bajo presión real de disponibilidad y escala. El día a día mezclaba arquitectura, desarrollo y evolución de infraestructura para aplicaciones distribuidas — incluyendo apoyo a squads en el diseño y la operación de clusters Elasticsearch. Automatizé el aprovisionamiento y la entrega con Terraform, Packer, Ansible y Docker sobre AWS, siempre con el mismo norte: rendimiento, confiabilidad y capacidad de crecer sin sorpresas en producción.',
				technologies: [
					'Python',
					'JavaScript',
					'Go',
					'C#',
					'AWS',
					'Terraform',
					'Packer',
					'Ansible',
					'Docker',
				],
			},
			{
				company: 'Nokia Networks',
				role: 'Ingeniero de Integración de Sistemas',
				period: 'Dic 2015 — Ago 2017',
				location: 'Río de Janeiro, Brasil',
				summary:
					'En Nokia integré sistemas para operadoras de telecom: desarrollar, aprovisionar, orquestar y configurar soluciones que debían conversar con entornos heterogéneos. Participé en integraciones IoT con terceros y en pipelines ETL con Greenplum y MySQL, conectando fuentes de datos a flujos operativos. Para reducir trabajo manual y riesgo, automatizé entornos Linux con Ansible y Shell Script, aplicando prácticas de cloud, Git, Elasticsearch y patrones de diseño pensados para escala y mantenibilidad.',
				technologies: [
					'Ansible',
					'Shell Script',
					'Linux',
					'MySQL',
					'Greenplum',
					'Elasticsearch',
					'Git',
				],
			},
			{
				company: 'Globo.com',
				role: 'Software Engineer',
				period: 'Nov 2014 — Nov 2015',
				location: 'Río de Janeiro, Brasil',
				summary:
					'En la plataforma de video de Globo.com construí y mantuve servicios backend y APIs para entrega en vivo y bajo demanda, con foco en rendimiento, escala y resiliencia — donde latencia y estabilidad importan de verdad. También contribuí con el equipo de DevOps en la automatización y la eficiencia de los pipelines de CI/CD, acortando el camino del código a producción. El trabajo transitaba por microservicios y sistemas distribuidos, con stack de datos, caché y balanceo (PostgreSQL, MongoDB, Redis, Elasticsearch, Nginx) sobre Python, Node.js y Docker.',
				technologies: [
					'Python',
					'Node.js',
					'JavaScript',
					'Redis',
					'Docker',
					'PostgreSQL',
					'MongoDB',
					'Elasticsearch',
					'Nginx',
				],
			},
			{
				company: 'Neemu',
				role: 'Software Developer',
				period: 'Feb 2013 — Oct 2014',
				location: 'Manaus, Brasil',
				summary:
					'En Neemu trabajé en el equipo de Big Data desarrollando servicios de adquisición de datos para sistemas escalables y distribuidos — bases que deben absorber volumen sin perder confiabilidad. También me sumé a DevOps, automatizando rutinas, mejorando pipelines de continuous delivery/deployment y operando recursos en AWS. El día a día mezclaba Node.js y JavaScript con MySQL, PostgreSQL, MongoDB y Redis, además de Shell Script en Linux, Docker y Git. Apliqué microservicios, patrones de diseño y prácticas de cloud para mantener rendimiento, escala y mantenibilidad en el centro de las decisiones.',
				technologies: [
					'Node.js',
					'JavaScript',
					'MySQL',
					'PostgreSQL',
					'MongoDB',
					'Redis',
					'Docker',
					'AWS',
					'Shell Script',
				],
			},
			{
				company: 'INdT',
				role: 'Software Developer',
				period: 'Abr 2012 — Feb 2013',
				location: 'Manaus, Brasil',
				summary:
					'En el INdT (Instituto Nokia de Tecnología) formé parte del equipo de Cloud & Backend, desarrollando servicios backend y aplicaciones mobile. Construí APIs REST escalables integradas a MySQL, usando Node.js, JavaScript, Java y C++ según el problema. Los entornos de desarrollo y producción corrían en Linux, con fuerte uso de Shell Script para automatización. Los proyectos exigían colaboración cercana con otros equipos, prácticas ágiles con Scrum y mejora continua de arquitectura y procesos — con Git y design patterns sosteniendo la mantenibilidad del código.',
				technologies: [
					'Node.js',
					'JavaScript',
					'Java',
					'C++',
					'MySQL',
					'Linux',
					'Shell Script',
					'Git',
				],
			},
		],
	},
	skills: {
		title: 'Competencias',
		groups: [
			{
				title: 'Backend & APIs',
				items: [
					'Node.js',
					'TypeScript',
					'NestJS',
					'Python',
					'Go',
					'C#',
					'REST',
					'Microservicios',
				],
			},
			{
				title: 'Arquitectura',
				items: [
					'Clean Code',
					'Arquitectura limpia',
					'Design patterns',
					'Sistemas distribuidos',
					'Escalabilidad',
					'Resiliencia',
				],
			},
			{
				title: 'Cloud & DevOps',
				items: [
					'AWS',
					'Docker',
					'Terraform',
					'Packer',
					'Ansible',
					'CI/CD',
					'Linux',
					'Shell Script',
				],
			},
			{
				title: 'Datos & Observabilidad',
				items: [
					'PostgreSQL',
					'MySQL',
					'MongoDB',
					'Redis',
					'Elasticsearch',
					'Datadog',
					'Métricas',
					'Logs',
				],
			},
		],
	},
	contributions: {
		title: 'Actividad en GitHub',
		summary: '{total} contribuciones públicas en el último año.',
		profileLink: 'Ver perfil en GitHub',
		legendLabel: 'Nivel de actividad',
		legendLess: 'Menos',
		legendMore: 'Más',
		contributionSingular: 'contribución',
		contributionPlural: 'contribuciones',
	},
	contact: {
		title: 'Contacto',
		body: 'Abierto a conversaciones sobre ingeniería, arquitectura y oportunidades. Prefiero email o LinkedIn.',
		ctaEmail: 'Enviar email',
		labels: {
			email: 'Email',
			linkedin: 'LinkedIn',
			github: 'GitHub',
			location: 'Ubicación',
		},
	},
	footer: {
		rights: 'Jonatas Pedraza. Todos los derechos reservados.',
		brandNote: 'Identidad visual: Mandril Solutions',
	},
	wire: {
		role: 'rol',
		name: 'nombre',
		summary: 'resumen',
		activityGithub: 'actividad / github',
		about: '01 / sobre mí',
		experience: '02 / experiencia',
		skills: '03 / competencias',
	},
};
