import type { PortfolioContent } from './types';

export const pt: PortfolioContent = {
	meta: {
		title: 'Jonatas Pedraza — Engenheiro de Software',
		description:
			'Engenheiro de Software com foco em backend, arquitetura, cloud e DevOps. Experiência em crédito, pagamentos, delivery, telecom e vídeo.',
	},
	nav: {
		about: 'Sobre',
		experience: 'Experiência',
		skills: 'Competências',
		contact: 'Contato',
		resume: 'Currículo',
		versionPreview: 'Versões de layout',
	},
	hero: {
		eyebrow: 'Jonatas Pedraza',
		headline: 'Engenheiro de Software',
		tagline:
			'Backend, frontend, arquitetura e cloud para produtos que precisam escalar com confiabilidade.',
		ctaContact: 'Fale comigo',
		ctaResume: 'Baixar currículo',
	},
	about: {
		title: 'Sobre',
		body: 'Engenheiro de Software com trajetória em backend, arquitetura e DevOps, construindo plataformas que precisam escalar com confiabilidade — crédito, pagamentos, delivery, telecom, vídeo e produtos orientados a dados. Atuo de ponta a ponta: do entendimento do problema e do desenho da solução à implementação, observabilidade e sustentação em produção. Perfil generalista com julgamento: escolho a ferramenta certa para o desafio, priorizo arquitetura sustentável e trabalho lado a lado com produto, design e operações. Uso ferramentas de IA generativa como alavancagem no dia a dia — para acelerar exploração e entrega — sem abrir mão da responsabilidade sobre trade-offs, qualidade e o que realmente chega à produção.',
	},
	experience: {
		title: 'Experiência',
		items: [
			{
				company: 'Nuvemshop',
				companyUrl: 'https://www.nuvemshop.com.br/',
				role: 'Software Engineer',
				period: 'Mar 2024 — Atual',
				location: 'São Paulo, Brasil',
				summary:
					'Na Nuvemshop atuo na evolução da plataforma de crédito — da oferta e gestão às operações do dia a dia. O trabalho atravessa backend e frontend: construo funcionalidades escaláveis e confiáveis, integro APIs de parceiros para o motor de crédito (comunicação entre sistemas, troca de dados e automação de análise e aprovação) e desenvolvo o frontend de crédito com React, TypeScript, Figma e Playwright, em parceria com design. Em um squad enxuto com produto, design e operações, também entrego ferramentas internas de backoffice que melhoram processos e aceleram valor. Quando algo quebra em produção, investigo com Datadog (métricas, logs e causa raiz) e uso ferramentas de IA generativa como alavancagem no fluxo de desenvolvimento — sem abrir mão da responsabilidade sobre qualidade e o que chega ao usuário.',
				technologies: [
					'TypeScript',
					'Node.js',
					'React',
					'Figma',
					'Playwright',
					'PostgreSQL',
					'Redis',
					'AWS',
					'Datadog',
				],
			},
			{
				company: 'Delivery Much Brasil',
				companyUrl: 'https://www.deliverymuch.com.br/',
				role: 'Software Architect',
				period: 'Jun 2021 — Fev 2024',
				location: 'Santa Catarina, Brasil',
				summary:
					'Como arquiteto, desenhei e implementei soluções de food delivery em microserviços na AWS, com atenção constante a escala, performance, segurança e manutenibilidade. Parte central do papel era traduzir o negócio em decisões técnicas: entrevistas, refinamentos e alinhamentos com stakeholders, gerando especificações claras para o time. Apoiei tech leads com padrões de código, documentação (diagramas e guias), integração contínua e práticas ágeis. Em momentos críticos, entrei hands-on em squads com legado e integrações complexas, ajudando a destravar entregas de alta prioridade sem perder o fio da arquitetura.',
				technologies: [
					'NestJS',
					'Node.js',
					'TypeScript',
					'Docker',
					'MongoDB',
					'PostgreSQL',
					'Redis',
					'Elasticsearch',
				],
			},
			{
				company: 'Pagar.me',
				companyUrl: 'https://www.pagar.me/',
				role: 'Software Engineer',
				period: 'Ago 2017 — Jun 2021',
				location: 'São Paulo, Brasil',
				summary:
					'No time de SRE da Pagar.me trabalhei em sistemas de pagamentos online sob pressão de disponibilidade e escala. O dia a dia misturava arquitetura, desenvolvimento e evolução de infraestrutura para aplicações distribuídas — incluindo apoio a squads na operação e no desenho de clusters Elasticsearch. Automatizei provisionamento e entrega com Terraform, Packer, Ansible e Docker sobre AWS, sempre com o mesmo norte: performance, confiabilidade e capacidade de crescer sem surpresas em produção.',
				technologies: [
					'Python',
					'JavaScript',
					'Go',
					'C#',
					'AWS',
					'Terraform',
					'Packer',
					'Ansible',
					'Docker',
				],
			},
			{
				company: 'Nokia Networks',
				companyUrl: 'https://www.nokia.com/networks/',
				role: 'System Integration Engineer',
				period: 'Dez 2015 — Ago 2017',
				location: 'Rio de Janeiro, Brasil',
				summary:
					'Na Nokia atuei na integração de sistemas para operadoras de telecom: desenvolver, provisionar, orquestrar e configurar soluções que precisavam conversar com ambientes heterogêneos. Participei de integrações IoT com terceiros e de pipelines ETL com Greenplum e MySQL, conectando fontes de dados a fluxos operacionais. Para reduzir trabalho manual e risco, automatizei ambientes Linux com Ansible e Shell Script, aplicando práticas de cloud, Git, Elasticsearch e padrões de projeto pensados para escala e manutenibilidade.',
				technologies: [
					'Ansible',
					'Shell Script',
					'Linux',
					'MySQL',
					'Greenplum',
					'Elasticsearch',
					'Git',
				],
			},
			{
				company: 'Globo.com',
				companyUrl: 'https://www.globo.com/',
				role: 'Software Engineer',
				period: 'Nov 2014 — Nov 2015',
				location: 'Rio de Janeiro, Brasil',
				summary:
					'Na plataforma de vídeo da Globo.com construí e mantive serviços backend e APIs para entrega ao vivo e sob demanda, com foco em performance, escala e resiliência — onde latência e estabilidade importam de verdade. Também contribuí com o time de DevOps na automação e na eficiência dos pipelines de CI/CD, encurtando o caminho do código à produção. O trabalho transitava por microserviços e sistemas distribuídos, com stack de dados, cache e balanceamento (PostgreSQL, MongoDB, Redis, Elasticsearch, Nginx) em cima de Python, Node.js e Docker.',
				technologies: [
					'Python',
					'Node.js',
					'JavaScript',
					'Redis',
					'Docker',
					'PostgreSQL',
					'MongoDB',
					'Elasticsearch',
					'Nginx',
				],
			},
			{
				company: 'Neemu',
				companyUrl: 'https://www.linx.com.br/',
				role: 'Software Developer',
				period: 'Fev 2013 — Out 2014',
				location: 'Manaus, Brasil',
				summary:
					'Na Neemu atuei no time de Big Data desenvolvendo serviços de aquisição de dados para sistemas escaláveis e distribuídos — o tipo de base que precisa absorver volume sem perder confiabilidade. Também integrei o time de DevOps, automatizando rotinas, melhorando pipelines de continuous delivery/deployment e operando recursos na AWS. O dia a dia misturava Node.js e JavaScript com MySQL, PostgreSQL, MongoDB e Redis, além de Shell Script em Linux, Docker e Git. Apliquei microserviços, padrões de projeto e práticas de cloud para manter performance, escala e manutenibilidade no centro das decisões.',
				technologies: [
					'Node.js',
					'JavaScript',
					'MySQL',
					'PostgreSQL',
					'MongoDB',
					'Redis',
					'Docker',
					'AWS',
					'Shell Script',
				],
			},
			{
				company: 'INdT',
				companyUrl: 'https://indt.org.br/',
				role: 'Software Developer',
				period: 'Abr 2012 — Fev 2013',
				location: 'Manaus, Brasil',
				summary:
					'No INdT (Instituto Nokia de Tecnologia) fiz parte do time de Cloud & Backend, desenvolvendo serviços backend e aplicações mobile. Construí APIs REST escaláveis integradas a MySQL, usando Node.js, JavaScript, Java e C++ conforme o problema pedia. Os ambientes de desenvolvimento e produção rodavam em Linux, com forte uso de Shell Script para automação. Os projetos exigiam colaboração próxima com outros times, práticas ágeis com Scrum e evolução contínua de arquitetura e processos — com Git e design patterns sustentando a manutenibilidade do código.',
				technologies: [
					'Node.js',
					'JavaScript',
					'Java',
					'C++',
					'MySQL',
					'Linux',
					'Shell Script',
					'Git',
				],
			},
		],
	},
	skills: {
		title: 'Competências',
		groups: [
			{
				title: 'Backend & APIs',
				items: [
					'Node.js',
					'TypeScript',
					'NestJS',
					'Python',
					'Go',
					'C#',
					'REST',
					'Microserviços',
				],
			},
			{
				title: 'Arquitetura',
				items: [
					'Clean Code',
					'Arquitetura limpa',
					'Design patterns',
					'Sistemas distribuídos',
					'Escalabilidade',
					'Resiliência',
				],
			},
			{
				title: 'Cloud & DevOps',
				items: [
					'AWS',
					'Docker',
					'Terraform',
					'Packer',
					'Ansible',
					'CI/CD',
					'Linux',
					'Shell Script',
				],
			},
			{
				title: 'Dados & Observabilidade',
				items: [
					'PostgreSQL',
					'MySQL',
					'MongoDB',
					'Redis',
					'Elasticsearch',
					'Datadog',
					'Métricas',
					'Logs',
				],
			},
		],
	},
	contributions: {
		title: 'Atividade no GitHub',
		summary: '{total} contribuições públicas no último ano.',
		profileLink: 'Ver perfil no GitHub',
		legendLabel: 'Nível de atividade',
		legendLess: 'Menos',
		legendMore: 'Mais',
		contributionSingular: 'contribuição',
		contributionPlural: 'contribuições',
	},
	contact: {
		title: 'Contato',
		body: 'Aberto a conversas sobre engenharia, arquitetura e oportunidades. Prefira e-mail ou LinkedIn.',
		ctaEmail: 'Enviar e-mail',
		labels: {
			email: 'E-mail',
			linkedin: 'LinkedIn',
			github: 'GitHub',
			location: 'Localização',
		},
	},
	footer: {
		rights: 'Jonatas Pedraza. Todos os direitos reservados.',
		brandNote: 'Identidade visual: Mandril Solutions',
	},
	wire: {
		role: 'cargo',
		name: 'nome',
		summary: 'resumo',
		activityGithub: 'atividade / github',
		about: '01 / sobre',
		experience: '02 / experiência',
		skills: '03 / competências',
	},
};
